import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * specs/42 R3.1 / R6 — acceptance greps for the palette namespace split.
 *
 * R3.1: components and theme sheets resolve only through role
 * (`--hz-color-*`) / intent (`--hz-intent-*`) tokens — `--hz-palette-*` is
 * referenced in exactly one place, the token source. Generated sheets
 * (tokens.css, and the example theme `*.css` overrides) are engine OUTPUT of
 * that source and are excluded, same as the example `*.config.ts` files
 * (ocean/terminal) — those are per-theme token SOURCES, the same tier
 * as `src/lib/tokens/index.ts`, and specs/42 R2.6 explicitly requires
 * terminal.config.ts's `phosphor` intent to read `var(--hz-palette-primary)`.
 * The hand-authored Docs example (specs/46, theme/examples/docs/docs.css)
 * has no config and is deliberately NOT excluded — it stays in scan scope,
 * resolving through role/intent tokens only, like any other hand-authored
 * sheet.
 *
 * R6: the old `--hz-color-<hue>` names (gray/primary/secondary/danger/
 * warning/success/info) no longer exist anywhere in `src/**` code.
 * `--hz-color-black`/`--hz-color-white` are excluded — they persist as
 * mode-invariant alias roles.
 */

const here = dirname(fileURLToPath(import.meta.url));
const srcRoot = join(here, '../../../src');

function walk(dir: string, out: string[] = []): string[] {
	for (const name of readdirSync(dir)) {
		const path = join(dir, name);
		if (statSync(path).isDirectory()) walk(path, out);
		else out.push(path);
	}
	return out;
}

const allSrcFiles = walk(srcRoot);

describe('specs/42 R3.1 — zero --hz-palette-* in components/theme (excluding generated sheets + example sources)', () => {
	// Generated engine OUTPUT — never hand-edited, regenerated by `pnpm gen:tokens`.
	const generatedSheets = new Set(
		[
			'lib/tokens/tokens.css',
			'lib/theme/examples/ocean.css',
			'lib/theme/examples/terminal/terminal.tokens.css'
		].map((p) => join(srcRoot, p))
	);
	// Per-theme token SOURCES — the same tier as tokens/index.ts (the sole
	// sanctioned palette consumer); specs/42 R2.6 requires a direct
	// --hz-palette-* reference in terminal.config.ts's phosphor intent.
	const exampleConfigSources = new Set(
		['lib/theme/examples/ocean.config.ts', 'lib/theme/examples/terminal/terminal.config.ts'].map(
			(p) => join(srcRoot, p)
		)
	);

	const scoped = allSrcFiles.filter(
		(f) =>
			(f.includes(join(srcRoot, 'lib/components')) || f.includes(join(srcRoot, 'lib/theme'))) &&
			/\.(css|svelte|ts)$/.test(f) &&
			!generatedSheets.has(f) &&
			!exampleConfigSources.has(f)
	);

	it('scanned a meaningful number of component/theme files', () => {
		expect(scoped.length).toBeGreaterThan(20);
	});

	it('contains zero --hz-palette-* references', () => {
		const hits: string[] = [];
		for (const file of scoped) {
			const content = readFileSync(file, 'utf8');
			const matches = content.match(/--hz-palette-[a-z0-9-]+/g);
			if (matches) {
				hits.push(`${file.slice(srcRoot.length + 1)}: ${[...new Set(matches)].join(', ')}`);
			}
		}
		expect(hits).toEqual([]);
	});
});

describe('specs/42 R6 — zero stale --hz-color-(gray|primary|secondary|danger|warning|success|info) in src/**', () => {
	const codeFiles = allSrcFiles.filter((f) => /\.(css|svelte|ts)$/.test(f));

	it('scanned a meaningful number of files', () => {
		expect(codeFiles.length).toBeGreaterThan(100);
	});

	it('contains zero stale role-shaped palette names (black/white excluded — they are roles)', () => {
		const stale = /--hz-color-(gray|primary|secondary|danger|warning|success|info)\b/g;
		const hits: string[] = [];
		for (const file of codeFiles) {
			const content = readFileSync(file, 'utf8');
			const matches = content.match(stale);
			if (matches) {
				hits.push(`${file.slice(srcRoot.length + 1)}: ${[...new Set(matches)].join(', ')}`);
			}
		}
		expect(hits).toEqual([]);
	});
});
