/**
 * @hyzer-labs/ui token engine — CSS emission.
 *
 * Deterministic: same resolved config → same bytes. Full mode renders the
 * complete tokens sheet (the committed `tokens.css` is this output with no
 * config); overrides mode emits only config-touched declarations as a patch
 * sheet, optionally scoped under a custom selector.
 */

import {
	HyzerConfigError,
	resolveConfig,
	toKebab,
	type HyzerThemeOverride,
	type ResolvedConfig,
	type ResolvedTheme,
	type SectionId,
	type TokenEntry
} from './schema.js';

export interface GenerateOptions {
	/**
	 * `full` (default) — a complete tokens sheet, imported instead of ours.
	 * `overrides` — only config-touched tokens, imported after ours.
	 */
	mode?: 'full' | 'overrides';
	/**
	 * Root selector (default `:root`). Use a class (e.g. `.theme-ocean`) to
	 * scope a theme to a subtree; the dark block composes with it.
	 */
	selector?: string;
	/**
	 * Extra description lines prepended inside the generated header comment —
	 * how the example sheets carry their name/usage prose.
	 */
	intro?: string[];
}

// ---------------------------------------------------------------------------
// Templates — section banners and per-token notes carried over from the
// hand-authored sheet so the generated file keeps its documentation value.
// ---------------------------------------------------------------------------

const SECTION_BANNERS: Record<SectionId, string[]> = {
	palette: ['Layer 1 — Palette (--hz-palette-*)', 'Single value per color; no per-color ramps.'],
	roles: [
		'Layer 2 — Semantic roles (light defaults)',
		'Reference the palette via var(); the dark block overrides these roles',
		'(and the status hues below) — the indirection point for theming.'
	],
	intent: [
		'Layer 2 — Intent roles',
		'The component-facing intent vocabulary (Button/Badge/Alert intents,',
		'field error states). Same indirection pattern as the roles above:',
		'override --hz-intent-* to retarget status colors specifically without',
		'touching the palette; override the palette and these follow.'
	],
	fontSize: ['Type scale'],
	typeSupport: ['Supporting type tokens'],
	space: ['Spacing — backs existing component fallbacks (values are fixed)'],
	width: [
		'Sizing / width — backs existing component fallbacks (values are fixed)',
		"Overriding these retunes Container max, Split's stackBelow threshold,",
		"and Grid's fluid { min } mode — all resolve via var(). Grid's BAND",
		'breakpoints (base/sm/md/lg) mirror these values but stay literal',
		'system constants: CSS cannot read custom properties in media or',
		'container queries.'
	],
	radius: ['Radius'],
	borderWidth: ['Border width'],
	shadow: ['Elevation'],
	zIndex: ['Z-index'],
	motion: ['Motion']
};

/** Inline notes emitted immediately before specific declarations. */
const TOKEN_NOTES: Record<string, string[]> = {
	'--hz-palette-success': [
		'Status hues tuned 2026-07-14 so every intent color passes WCAG AA',
		'(≥ 4.5:1) as text on both light surfaces — and so white text passes',
		'on every solid intent background.'
	],
	'--hz-color-surface-muted': [
		'Subdued opaque surface (code blocks, footer, quiet panels): gray mixed',
		"over surface, so it tracks surface overrides and covers what's behind",
		'it. The dark block strengthens the mix — 6% is invisible over black.'
	],
	'--hz-density': [
		'Density grid unit — drives --hz-space-near/--hz-space-away (see the',
		'density spacing block below). Override to retune every distance.'
	]
};

const FULL_HEADER = [
	'/**',
	' * @hyzer-labs/ui design tokens',
	' *',
	' * GENERATED FILE — do not edit by hand.',
	' * Generated by `hyzer generate` from your hyzer.config. Regenerate rather',
	' * than editing here — any hand edits are lost on the next run.',
	' *',
	' * CSS custom properties — the primary token format.',
	' * Two-layer color model: palette (Layer 1) + semantic roles (Layer 2).',
	' */'
].join('\n');

const DENSITY_COMMENT = [
	'/* ==========================================================================',
	' * Density spacing — adapted from "Complementary Space"',
	' * (https://blog.damato.design/posts/complementary-space/).',
	' * Two distances: --hz-space-near separates related things, --hz-space-away',
	' * separates unrelated things; both derive from the --hz-density grid unit.',
	' * Each data-density-shift ancestor tightens the pair one step, so nested',
	' * regions read denser without new spacing values. The near multipliers walk',
	" * the 1-2-5-10 ladder, and a shifted region's away always equals its",
	" * parent's near. Coexists with the fixed --hz-space-* scale above.",
	' * ========================================================================== */'
].join('\n');

const DARK_COMMENT = [
	'/* ==========================================================================',
	' * Dark theme — authored entirely at the palette/role layer (the two-tier',
	" * rule). Surface and text flip, surface-muted's gray tint strengthens (6%",
	' * is invisible over black), and every hue lightens to a companion that',
	' * keeps WCAG AA (≥ 4.5:1) as text on both dark surfaces. The companions',
	' * are authored literals: the single-value palette ships no light ramp to',
	' * reference. Setting data-theme="dark" on ANY element themes that subtree.',
	' * ========================================================================== */'
].join('\n');

/** Emitted inside every theme block, before the re-declared derived chain. */
const DERIVED_COMMENT = [
	'Derived chain, re-declared. Layer 2 is var() indirection, and var() in a',
	'custom property resolves on the element the declaration applies to — so a',
	'chain declared at :root has already computed to the DEFAULT palette and',
	'inherits down as a fixed value. Re-declaring it here re-resolves it',
	"against this theme's own hues on whatever element carries the attribute,",
	'which is what makes a themed <section> work and not just a themed <html>.'
];

const SYSTEM_COMMENT = [
	'/* ==========================================================================',
	' * System preference — dark by default, until an explicit choice is made.',
	' * :not([data-theme]) is what makes the choice win: set data-theme="light"',
	' * (or "dark") anywhere on <html> and this block stops matching, so no',
	' * script is needed to FOLLOW the system, only to OVERRIDE it. Scoped to',
	' * :root because it only ever answers "what should the page default to".',
	' * ========================================================================== */'
].join('\n');

const LIGHT_COMMENT = [
	'/* ==========================================================================',
	' * Light theme — the default block, re-declared so it can be RESTORED.',
	' * :root defaults inherit as computed values, so a light section inside a',
	' * dark page would otherwise keep the dark values it inherited: there has',
	' * to be something to switch back TO. Only tokens some theme actually',
	' * changes are listed — the rest were never at risk.',
	' * ========================================================================== */'
].join('\n');

/** Per-theme block banner. */
function themeComment(name: string): string {
	return [
		'/* ==========================================================================',
		` * Theme "${name}" — activated by data-theme="${name}" on any element.`,
		' * ========================================================================== */'
	].join('\n');
}

// ---------------------------------------------------------------------------
// Emission helpers
// ---------------------------------------------------------------------------

function banner(lines: string[], indent: string): string {
	const bar = '='.repeat(69);
	return [
		`${indent}/* ${bar}`,
		...lines.map((l) => `${indent} * ${l}`),
		`${indent} * ${bar} */`
	].join('\n');
}

function note(lines: string[], indent: string): string {
	if (lines.length === 1) return `${indent}/* ${lines[0]} */`;
	return (
		[`${indent}/* ${lines[0]}`, ...lines.slice(1).map((l) => `${indent} * ${l}`)].join('\n') + ' */'
	);
}

function declarations(entries: TokenEntry[], indent: string, withNotes: boolean): string[] {
	const out: string[] = [];
	for (const entry of entries) {
		const noteLines = withNotes ? TOKEN_NOTES[entry.cssName] : undefined;
		if (noteLines) out.push(note(noteLines, indent));
		out.push(`${indent}${entry.cssName}: ${entry.value};`);
	}
	return out;
}

function densityBlock(resolved: ResolvedConfig): string {
	const rules = resolved.density.levels.map((level, depth) => {
		const selector = depth === 0 ? 'body' : `body ${'[data-density-shift] '.repeat(depth).trim()}`;
		return [
			`${selector} {`,
			`\t--hz-space-near: calc(var(--hz-density) * ${level.near});`,
			`\t--hz-space-away: calc(var(--hz-density) * ${level.away});`,
			'}'
		].join('\n');
	});
	return rules.join('\n\n');
}

/**
 * Theme-block selector: plain hook at :root, compound + descendant when scoped
 * (the scope element may carry data-theme itself, or inherit it from an
 * ancestor like <html>).
 *
 * The scoped pair is emitted one selector per line: generated sheets are
 * committed, so `prettier --check .` sees them, and a comma-joined pair of
 * this length is exactly what Prettier would break. Matching its output keeps
 * the drift test and the lint suite from contradicting each other.
 */
function themeSelector(selector: string, name: string): string {
	if (selector === ':root') return `[data-theme='${name}']`;
	return `${selector}[data-theme='${name}'],\n[data-theme='${name}'] ${selector}`;
}

/** Custom-property names referenced by var() inside a token value. */
function varRefs(value: string): string[] {
	return [...value.matchAll(/var\(\s*(--[a-z0-9-]+)/gi)].map((m) => m[1]);
}

/**
 * The tokens a SCOPED override sheet must re-declare: everything the config
 * touched, plus the transitive closure of tokens whose values depend on them.
 *
 * Why this exists. The two-layer color model is built on indirection —
 * `--hz-intent-primary: var(--hz-palette-primary)` — and var() inside a custom
 * property is substituted at computed-value time ON THE ELEMENT THE
 * DECLARATION APPLIES TO. At `:root` that is exactly what we want: an
 * override of `--hz-palette-primary` lands on the same element as the intent
 * declaration, so the cascade picks the new value and the whole chain
 * re-resolves.
 *
 * Scoped to a class it breaks. `.theme-ocean { --hz-palette-primary: #0f766e }`
 * leaves `--hz-intent-primary` declared back at `:root`, where it already
 * computed to the BASE blue and inherits down as that resolved value — so
 * every component reading the intent vocabulary (Button, Badge, Alert) keeps
 * the base palette while the panel swears it is teal.
 *
 * Re-emitting the dependents under the scope re-resolves them against the
 * scope's own values. The seed includes dark-block entries: a hue overridden
 * only in dark still needs its intent chain declared locally, or the dark
 * block has nothing to feed.
 */
function closureFrom(resolved: ResolvedConfig, seed: Iterable<string>): Set<string> {
	const included = new Set<string>(seed);
	const all = resolved.sections.flatMap((s) => s.entries);
	for (let changed = true; changed; ) {
		changed = false;
		for (const e of all) {
			if (included.has(e.cssName)) continue;
			if (varRefs(e.value).some((ref) => included.has(ref))) {
				included.add(e.cssName);
				changed = true;
			}
		}
	}
	return included;
}

function scopedClosure(resolved: ResolvedConfig): Set<string> {
	const seed: string[] = [];
	for (const section of resolved.sections) {
		for (const e of section.entries) if (e.fromConfig) seed.push(e.cssName);
	}
	for (const e of themeOwn(resolved.dark)) {
		if (e.fromConfig) seed.push(e.cssName);
	}
	return closureFrom(resolved, seed);
}

/** A theme's own declarations, in emission order (roles, hues, intents). */
function themeOwn(theme: ResolvedTheme): TokenEntry[] {
	return [...theme.color, ...theme.palette, ...theme.intent];
}

/**
 * A theme block: what the theme itself declares, plus the derived chain it
 * must re-declare to work on ANY element rather than only on `<html>`.
 *
 * Why the dependents exist. `--hz-intent-primary: var(--hz-palette-primary)`
 * is declared at `:root`, and var() inside a custom property is substituted
 * at computed-value time on the element the declaration applies to. When the
 * theme block lands on `<html>` — the same element as `:root` — the override
 * and the chain meet there and everything re-resolves. Land it on a
 * `<section>` instead and the intents have already computed at `:root` to the
 * default palette, inheriting down as fixed values: a dark section with
 * light-blue buttons and light borders. Re-declaring the dependents inside
 * the block re-resolves them against the theme's own values, on whatever
 * element the block matched. At `:root` they are identical to the defaults
 * and cost nothing but bytes.
 *
 * This is the same problem `scopedClosure()` solves for scoped sheets, from
 * the other direction: there the SHEET is scoped, here the BLOCK is.
 */
function themeBlock(
	resolved: ResolvedConfig,
	theme: ResolvedTheme
): { own: TokenEntry[]; dependents: TokenEntry[] } {
	const own = themeOwn(theme);
	const ownNames = new Set(own.map((e) => e.cssName));
	const closure = closureFrom(resolved, ownNames);
	const dependents = resolved.sections
		.flatMap((s) => s.entries)
		.filter((e) => closure.has(e.cssName) && !ownNames.has(e.cssName));
	return { own, dependents };
}

// ---------------------------------------------------------------------------
// generateCss
// ---------------------------------------------------------------------------

export function generateCss(resolved: ResolvedConfig, options: GenerateOptions = {}): string {
	const mode = options.mode ?? 'full';
	const selector = options.selector ?? ':root';
	return mode === 'full'
		? generateFull(resolved, selector, options.intro)
		: generateOverrides(resolved, selector, options.intro);
}

/** Weave optional intro lines into a generated header comment. */
function withIntro(header: string, intro: string[] | undefined): string {
	if (!intro || intro.length === 0) return header;
	const lines = header.split('\n');
	// After the opening '/**': the intro block, a spacer, then the stock text.
	return [lines[0], ...intro.map((l) => ` * ${l}`.trimEnd()), ' *', ...lines.slice(1)].join('\n');
}

function generateFull(resolved: ResolvedConfig, selector: string, intro?: string[]): string {
	const parts: string[] = [withIntro(FULL_HEADER, intro), `${selector} {`];

	resolved.sections.forEach((section, i) => {
		if (i > 0) parts.push('');
		parts.push(banner(SECTION_BANNERS[section.id], '\t'));
		parts.push(...declarations(section.entries, '\t', true));
		if (section.id === 'space') {
			parts.push('');
			parts.push(note(TOKEN_NOTES['--hz-density'], '\t'));
			parts.push(`\t--hz-density: ${resolved.density.unit};`);
		}
	});
	parts.push('}');

	parts.push('', DENSITY_COMMENT, densityBlock(resolved));

	// Every named theme is a [data-theme="<name>"] block of the same shape;
	// dark is one of them, and leads because the base itself authors it.
	const blocks = [resolved.dark, ...resolved.themes].map((theme) => ({
		theme,
		...themeBlock(resolved, theme)
	}));

	for (const { theme, own, dependents } of blocks) {
		const comment = theme.name === 'dark' ? DARK_COMMENT : themeComment(theme.name);
		parts.push('', comment, `${themeSelector(selector, theme.name)} {`);
		// Roles, then hues, then intents — sourced directly from the three
		// resolved lists (.3); no value-shape inference.
		parts.push(...declarations(theme.color, '\t', false));
		for (const group of [theme.palette, theme.intent]) {
			if (group.length === 0) continue;
			parts.push('');
			parts.push(...declarations(group, '\t', false));
		}
		if (dependents.length > 0) {
			parts.push('');
			parts.push(note(DERIVED_COMMENT, '\t'));
			parts.push(...declarations(dependents, '\t', false));
		}
		parts.push('}');

		// The system default carries the theme's OWN declarations only: it
		// applies at :root, where the chain declared above it re-resolves on
		// the same element, so the derived block would be pure duplication.
		if (theme.name === 'dark' && selector === ':root') {
			parts.push('', SYSTEM_COMMENT, '@media (prefers-color-scheme: dark) {');
			parts.push('\t:root:not([data-theme]) {');
			parts.push(...declarations(own, '\t\t', false));
			parts.push('\t}');
			parts.push('}');
		}
	}

	const restore = lightRestore(resolved, blocks);
	if (restore.length > 0) {
		parts.push('', LIGHT_COMMENT, `${themeSelector(selector, 'light')} {`);
		parts.push(...declarations(restore, '\t', false));
		parts.push('}');
	}

	return parts.join('\n') + '\n';
}

/**
 * The `[data-theme="light"]` block: every token any theme block declares,
 * restored to its default value.
 *
 * A token a theme introduces but `:root` never defines (a consumer's
 * dark-only intent, say) restores to `initial` — the guaranteed-invalid
 * value, which is what "not declared here" means for a custom property, so
 * `var()` falls back exactly as it does outside the theme.
 */
function lightRestore(
	resolved: ResolvedConfig,
	blocks: { own: TokenEntry[]; dependents: TokenEntry[] }[]
): TokenEntry[] {
	const changed = new Set<string>();
	for (const block of blocks) {
		for (const e of [...block.own, ...block.dependents]) changed.add(e.cssName);
	}
	// :root order, so the block reads like the sheet it restores; tokens no
	// :root section defines follow at the end.
	const rootEntries = resolved.sections.flatMap((s) => s.entries);
	const defined = new Set(rootEntries.map((e) => e.cssName));
	return [
		...rootEntries.filter((e) => changed.has(e.cssName)),
		...[...changed]
			.filter((cssName) => !defined.has(cssName))
			.map((cssName) => ({ cssName, key: cssName, value: 'initial', fromConfig: false }))
	];
}

function generateOverrides(resolved: ResolvedConfig, selector: string, intro?: string[]): string {
	const scoped = selector !== ':root';
	const header = withIntro(
		[
			'/**',
			' * @hyzer-labs/ui token overrides',
			' *',
			' * GENERATED FILE — do not edit by hand (hyzer generate --mode overrides).',
			...(scoped
				? [
						' * Config-touched tokens plus every token that derives from them: a',
						' * scoped sheet must re-declare the derived Layer-2 chain, because a',
						' * var() indirection declared at :root already resolved there and',
						' * inherits down as a fixed value.',
						' * Import this sheet AFTER @hyzer-labs/ui/tokens.css so the overrides',
						' * win by source order.'
					]
				: [
						' * Only config-touched tokens are emitted; import this sheet AFTER',
						' * @hyzer-labs/ui/tokens.css so the overrides win by source order.'
					]),
			' */'
		].join('\n'),
		intro
	);

	// Scoped sheets carry the derived chain too — see scopedClosure().
	const emit = scoped ? scopedClosure(resolved) : null;
	const rootEntries = resolved.sections.flatMap((s) =>
		s.entries.filter((e) => (emit ? emit.has(e.cssName) : e.fromConfig))
	);

	/**
	 * The dark block needs the same treatment for a different reason. A base
	 * dark entry like surface-muted's stronger tint
	 * (`color-mix(… var(--hz-palette-gray) 25%, var(--hz-color-surface))`) is
	 * declared at :root's dark block. Scoped, it never reaches the subtree, and
	 * the scope's own light-block declaration would silently keep applying its
	 * 6% light-mode tint in dark. Re-emit any dark entry that derives from a
	 * token the scope redeclares.
	 */
	const darkDerives = (e: TokenEntry) =>
		emit !== null && varRefs(e.value).some((ref) => emit.has(ref));
	const darkEntries = [
		...resolved.dark.color.filter((e) => e.fromConfig || darkDerives(e)),
		...resolved.dark.palette.filter((e) => e.fromConfig || darkDerives(e)),
		...resolved.dark.intent.filter((e) => e.fromConfig || darkDerives(e))
	];

	const parts: string[] = [header];
	const hasRoot = rootEntries.length > 0 || resolved.density.unitFromConfig;

	/**
	 * The light block below re-restores the tokens this sheet overrides, and it
	 * draws them from `rootEntries` — the same names with the same values. When
	 * every restored token is one this sheet already declares at the root, the
	 * two blocks would carry identical declarations, so they share one rule
	 * instead. Any token the root declares and light does not is a token no
	 * theme changes, which makes declaring it under light harmless.
	 */
	const restorableNames = new Set(
		lightRestore(resolved, [
			themeBlock(resolved, resolved.dark),
			...resolved.themes.map((theme) => themeBlock(resolved, theme))
		]).map((e) => e.cssName)
	);
	const mergeLight =
		hasRoot &&
		rootEntries.some((e) => restorableNames.has(e.cssName)) &&
		!resolved.density.unitFromConfig;

	if (hasRoot) {
		parts.push(
			mergeLight ? `${selector},\n${themeSelector(selector, 'light')} {` : `${selector} {`
		);
		parts.push(...declarations(rootEntries, '\t', false));
		if (resolved.density.unitFromConfig) parts.push(`\t--hz-density: ${resolved.density.unit};`);
		parts.push('}');
	}
	if (darkEntries.length > 0) {
		if (hasRoot) parts.push('');
		parts.push(`${themeSelector(selector, 'dark')} {`);
		parts.push(...declarations(darkEntries, '\t', false));
		parts.push('}');
	}

	// Named themes are entirely the consumer's authoring — every entry is
	// fromConfig, so the whole block is an override by definition. Each still
	// carries its derived chain, for the same reason the full sheet's do.
	let emitted = hasRoot || darkEntries.length > 0;
	const themeBlocks = resolved.themes.map((theme) => ({ theme, ...themeBlock(resolved, theme) }));
	for (const { theme, own, dependents } of themeBlocks) {
		if (own.length === 0) continue;
		if (emitted) parts.push('');
		parts.push(`${themeSelector(selector, theme.name)} {`);
		parts.push(...declarations(own, '\t', false));
		if (dependents.length > 0) {
			parts.push('');
			parts.push(note(DERIVED_COMMENT, '\t'));
			parts.push(...declarations(dependents, '\t', false));
		}
		parts.push('}');
		emitted = true;
	}

	// The base sheet's light block restores the BASE defaults — which would
	// undo this sheet's own :root overrides inside a light-scoped section.
	// Re-restore the tokens this sheet redeclares, after it in source order.
	const restorable = new Set(
		lightRestore(resolved, [themeBlock(resolved, resolved.dark), ...themeBlocks]).map(
			(e) => e.cssName
		)
	);
	const restore = mergeLight ? [] : rootEntries.filter((e) => restorable.has(e.cssName));
	if (restore.length > 0) {
		if (emitted) parts.push('');
		parts.push(`${themeSelector(selector, 'light')} {`);
		parts.push(...declarations(restore, '\t', false));
		parts.push('}');
		emitted = true;
	}

	if (!emitted) {
		parts.push('/* No overrides configured. */');
	}
	return parts.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// themeVars — the same block, as a flat map for runtime use
// ---------------------------------------------------------------------------

/**
 * The custom properties a theme override sets, resolved and flattened: the
 * theme's own declarations plus the derived chain, exactly what the generated
 * `[data-theme="…"]` block contains.
 *
 * Backs the inline form of the `theme()` attachment, which writes these
 * straight onto an element's `style`. The derived chain matters just as much
 * there as it does in a stylesheet — inline custom properties are still
 * declarations on one element, so an inline palette override without its
 * chain themes the surface and leaves the buttons behind.
 *
 * Throws `HyzerConfigError` on an invalid override, same as `resolveConfig`.
 */
export function themeVars(override: HyzerThemeOverride): Record<string, string> {
	const resolved = resolveConfig({ themes: { runtime: override } });
	const { own, dependents } = themeBlock(resolved, resolved.themes[0]);
	return Object.fromEntries([...own, ...dependents].map((e) => [e.cssName, e.value]));
}

// ---------------------------------------------------------------------------
// generateUtilitiesCss — the opt-in utility sheet
// ---------------------------------------------------------------------------

export interface GenerateUtilitiesOptions {
	/**
	 * Extra description lines prepended inside the generated header comment —
	 * same weaving as `GenerateOptions.intro`.
	 */
	intro?: string[];
}

const UTILITIES_HEADER = [
	'/**',
	' * @hyzer-labs/ui utilities',
	' *',
	' * GENERATED FILE — do not edit by hand.',
	' * Generated by `hyzer generate --utilities` (or set `utilities` in your',
	' * hyzer.config) from your tokens. Regenerate rather than editing here —',
	' * any hand edits are lost on the next run.',
	' *',
	' * Opt-in — import this sheet explicitly, like a theme sheet',
	' * (`@hyzer-labs/ui/utilities.css`). A consumer who never imports it ships',
	' * zero of these bytes.',
	' *',
	' * Definition: a utility class is a token-derived, single-property',
	' * helper — one class, one declaration, resolved from a design token.',
	' * That is the whole definition; it does not depend on where the class',
	' * is or is not used.',
	' *',
	' * Anti-goal: utilities are for ad-hoc spots — nudging one element,',
	' * tinting one line of text — not an alternative layout system.',
	' * Components already own their spacing (gap/padding props, the',
	' * data-padding/data-gap scales) and the density system',
	' * (--hz-space-near/--hz-space-away). The utility sheet deliberately',
	' * does not reproduce that surface: it exposes the fixed --hz-space-*',
	' * scale for margins only, never the density near/away distances, and',
	' * no padding helpers at all (padding is owned by components).',
	' *',
	' * Unlayered, single-class specificity (0,1,0), no !important — mirrors',
	' * .sr-only: a deliberately-applied utility beats the layered reference',
	" * theme, while a consumer's own unlayered class of equal specificity",
	' * still wins by source order.',
	' */'
].join('\n');

const COLOR_UTILITIES_BANNER = [
	'Color utilities',
	'Role + intent helpers for text, background, border and fill, resolved from',
	'--hz-color-* / --hz-intent-*. One property each: .hz-border-* sets only',
	'border-color, so bring your own border-width/style; .hz-fill-* is for SVG.',
	'Components that own a surface (Badge, Alert, Banner) keep doing so — these',
	'are for ad-hoc spots, not for restyling a component.'
];

/**
 * The four color-utility families, fixed emission order. Each emits its
 * role helpers first, then one class per resolved intent. A `suffix` of `''`
 * is the bare family class (`.hz-text`, `.hz-bg`).
 */
const COLOR_FAMILIES: readonly {
	prefix: string;
	property: string;
	roles: readonly { suffix: string; role: string }[];
}[] = [
	{
		prefix: 'hz-text',
		property: 'color',
		roles: [
			{ suffix: '', role: 'text' },
			{ suffix: 'muted', role: 'textMuted' }
		]
	},
	{
		prefix: 'hz-bg',
		property: 'background-color',
		roles: [
			{ suffix: '', role: 'surface' },
			{ suffix: 'muted', role: 'surfaceMuted' }
		]
	},
	{
		prefix: 'hz-border',
		property: 'border-color',
		roles: [{ suffix: '', role: 'border' }]
	},
	{
		prefix: 'hz-fill',
		property: 'fill',
		roles: [
			{ suffix: '', role: 'text' },
			{ suffix: 'muted', role: 'textMuted' }
		]
	}
];

const MARGIN_UTILITIES_BANNER = [
	'Margin utilities (logical properties)',
	'Seven families per --hz-space-* rung: margin, margin-block(-start/-end),',
	'margin-inline(-start/-end). No padding — padding is owned by components.'
];

/** The seven logical margin families, fixed emission order. */
const MARGIN_FAMILIES: readonly { suffix: string; property: string }[] = [
	{ suffix: '', property: 'margin' },
	{ suffix: 'block', property: 'margin-block' },
	{ suffix: 'block-start', property: 'margin-block-start' },
	{ suffix: 'block-end', property: 'margin-block-end' },
	{ suffix: 'inline', property: 'margin-inline' },
	{ suffix: 'inline-start', property: 'margin-inline-start' },
	{ suffix: 'inline-end', property: 'margin-inline-end' }
];

function utilityRule(className: string, property: string, value: string): string {
	return `.${className} {\n\t${property}: ${value};\n}`;
}

/**
 * Renders the opt-in utility sheet from the resolved token model: four color
 * families (`hz-text`, `hz-bg`, `hz-border`, `hz-fill`), each emitting its
 * role helpers plus one class per resolved intent, and the seven logical
 * margin families per resolved space rung.
 * Deterministic and unlayered — mirrors `.sr-only`'s specificity posture.
 * Does NOT re-resolve tokens; reads only `resolved.sections`.
 */
export function generateUtilitiesCss(
	resolved: ResolvedConfig,
	options: GenerateUtilitiesOptions = {}
): string {
	const roles = resolved.sections.find((s) => s.id === 'roles')!.entries;
	const intentEntries = resolved.sections.find((s) => s.id === 'intent')!.entries;
	const spaceEntries = resolved.sections.find((s) => s.id === 'space')!.entries;

	const parts: string[] = [withIntro(UTILITIES_HEADER, options.intro)];

	// --- color utilities --------------------------------------------------
	parts.push('', banner(COLOR_UTILITIES_BANNER, ''));

	for (const family of COLOR_FAMILIES) {
		// Utility-class-namespace collision tracking, per family (edge case: a
		// consumer intent named "muted" kebab-cases to the fixed .hz-text-muted
		// role helper's class name) — a hard generation error naming both
		// parties, mirroring the engine's existing kebab-collision rule
		// (schema.ts).
		const usedClasses = new Map<string, string>();

		for (const { suffix, role } of family.roles) {
			const entry = roles.find((e) => e.key === role);
			if (!entry) {
				throw new HyzerConfigError(
					`generateUtilitiesCss requires the "${role}" color role (for the .${family.prefix} utility family).`
				);
			}
			const className = suffix ? `${family.prefix}-${suffix}` : family.prefix;
			usedClasses.set(className, `the "${role}" role helper (.${className})`);
			parts.push('', utilityRule(className, family.property, `var(${entry.cssName})`));
		}

		for (const entry of intentEntries) {
			const className = `${family.prefix}-${toKebab(entry.key)}`;
			const owner = usedClasses.get(className);
			if (owner) {
				throw new HyzerConfigError(
					`config.tokens.intent.${entry.key} kebab-cases to the utility class ".${className}", ` +
						`which ${owner} already defines. Rename the intent to avoid the collision.`
				);
			}
			usedClasses.set(className, `intent "${entry.key}" (config.tokens.intent.${entry.key})`);
			parts.push('', utilityRule(className, family.property, `var(${entry.cssName})`));
		}
	}

	// --- margin utilities -------------------------------------------------
	parts.push('', banner(MARGIN_UTILITIES_BANNER, ''));
	for (const family of MARGIN_FAMILIES) {
		for (const rung of spaceEntries) {
			const rungSuffix = toKebab(rung.key);
			const className = family.suffix
				? `hz-m-${family.suffix}-${rungSuffix}`
				: `hz-m-${rungSuffix}`;
			parts.push('', utilityRule(className, family.property, `var(${rung.cssName})`));
		}
	}

	return parts.join('\n') + '\n';
}
