/**
 * @hyzer-labs/ui token engine — CSS emission.
 *
 * Deterministic: same resolved config → same bytes. Full mode renders the
 * complete tokens sheet (the committed `tokens.css` is this output with no
 * config); overrides mode emits only config-touched declarations as a patch
 * sheet, optionally scoped under a custom selector.
 */

import {
	HyzerConfigError,
	resolveConfig,
	toKebab,
	assertSelector,
	type HyzerThemeOverride,
	type ResolvedConfig,
	type ResolvedTheme,
	type SectionId,
	type TokenEntry
} from './schema.js';
import { intent as baseIntent } from '../tokens/index.js';
import { componentHooks, ROOT } from '../tokens/hooks.js';

export interface GenerateOptions {
	/**
	 * `full` (default) — a complete tokens sheet, imported instead of ours.
	 * `overrides` — only config-touched tokens, imported after ours.
	 */
	mode?: 'full' | 'overrides';
	/**
	 * Root selector (default `:root`). Use a class (e.g. `.theme-ocean`) to
	 * scope a theme to a subtree; the dark block composes with it.
	 */
	selector?: string;
	/**
	 * Extra description lines prepended inside the generated header comment —
	 * how the example sheets carry their name/usage prose.
	 */
	intro?: string[];
}

// ---------------------------------------------------------------------------
// Templates — section banners and per-token notes carried over from the
// hand-authored sheet so the generated file keeps its documentation value.
// ---------------------------------------------------------------------------

const SECTION_BANNERS: Record<SectionId, string[]> = {
	palette: [
		'Layer 1 - Palette (--hz-palette-*)',
		'One value per color here. Ramps are supported and simply not shipped:',
		'nest steps under a hue in your config to generate --hz-palette-<hue>-<step>.'
	],
	roles: [
		'Layer 2 - Semantic roles (light defaults)',
		'Reference the palette via var(). The dark block overrides these roles',
		'and the status hues below. This is the indirection point for theming.'
	],
	intent: [
		'Layer 2 - Intent roles',
		'The component-facing intent vocabulary (Button/Badge/Alert intents,',
		'field error states). Same indirection pattern as the roles above:',
		'override --hz-intent-* to retarget status colors without touching',
		'the palette; override the palette and these follow.'
	],
	fontSize: ['Type scale'],
	typeSupport: ['Supporting type tokens'],
	space: ['Spacing (fixed values)', 'Backs the fallbacks components already carry.'],
	width: [
		'Sizing / width (fixed values)',
		'Backs the fallbacks components already carry. Overriding these retunes',
		"Container max, Split's stackBelow threshold and Grid's fluid { min }",
		"mode, which all resolve via var(). Grid's BAND breakpoints",
		'(base/sm/md/lg) mirror these values but stay literal system constants:',
		'CSS cannot read custom properties in media or container queries.'
	],
	radius: ['Radius'],
	borderWidth: ['Border width'],
	shadow: ['Elevation'],
	zIndex: ['Z-index'],
	motion: ['Motion']
};

/** Inline notes emitted immediately before specific declarations. */
const TOKEN_NOTES: Record<string, string[]> = {
	'--hz-palette-success': [
		'Every intent color passes WCAG AA (>= 4.5:1) as text on both light',
		'surfaces. White text passes on every solid intent background.'
	],
	'--hz-color-surface-muted': [
		'Subdued opaque surface (code blocks, footer, quiet panels): gray mixed',
		"over surface, so it tracks surface overrides and covers what's behind",
		'it. The dark block strengthens the mix, because 6% is invisible',
		'over black.'
	],
	'--hz-density': [
		'The density grid unit. It drives --hz-space-near/--hz-space-away',
		'(see the density spacing block below). Override it to retune every',
		'distance.'
	]
};

const FULL_HEADER = [
	'/**',
	' * @hyzer-labs/ui design tokens',
	' *',
	' * GENERATED FILE - do not edit by hand.',
	' * Generated by `hyzer generate` from your hyzer.config. Regenerate rather',
	' * than editing here: any hand edits are lost on the next run.',
	' *',
	' * CSS custom properties are the primary token format.',
	' * Two-layer color model: palette (Layer 1) + semantic roles (Layer 2).',
	' */'
].join('\n');

const DENSITY_COMMENT = [
	'/* ==========================================================================',
	' * Density spacing, adapted from "Complementary Space"',
	' * (https://blog.damato.design/posts/complementary-space/).',
	' * Two distances: --hz-space-near separates related things, --hz-space-away',
	' * separates unrelated things. Both derive from the --hz-density grid unit.',
	' * Each data-density-shift ancestor tightens the pair one step, so nested',
	' * regions read denser without new spacing values. The near multipliers walk',
	" * the 1-2-5-10 ladder, and a shifted region's away always equals its",
	" * parent's near. This coexists with the fixed --hz-space-* scale above.",
	' * Looking for --hz-density-ladder-depth-1..4? This sheet never declares',
	' * them. Each appears below only as a var() fallback, and that includes any',
	' * value you set in the config: what you configured is the fallback you see.',
	' * That is deliberate. Declare a rung in your own CSS and it wins outright,',
	' * because no declaration here competes with it. Depth 1 is the unshifted',
	' * body; depth 4 is three data-density-shift ancestors deep.',
	' * ========================================================================== */'
].join('\n');

const DARK_COMMENT = [
	'/* ==========================================================================',
	' * Dark theme, authored entirely at the palette/role layer (the two-tier',
	' * rule). Surface and text flip. The gray tint on surface-muted',
	' * strengthens, because 6% is invisible over black. Every hue lightens to',
	' * a companion that keeps WCAG AA (>= 4.5:1) as text on both dark',
	' * surfaces. The companions are authored literals: the single-value',
	' * palette ships no light ramp to reference. Setting data-theme="dark" on',
	' * ANY element themes that subtree.',
	' * ========================================================================== */'
].join('\n');

/** Emitted inside every theme block, before the re-declared derived chain. */
const DERIVED_COMMENT = [
	'Derived chain, re-declared. Layer 2 is var() indirection, and var() in a',
	'custom property resolves on the element the declaration applies to. So a',
	'chain declared at :root has already computed to the DEFAULT palette, and',
	'inherits down as a fixed value. Re-declaring it here re-resolves it',
	"against this theme's own hues, on whatever element carries the attribute.",
	'That is what makes a themed <section> work, not only a themed <html>.'
];

/** System-preference banner — only the default's `data-theme` value interpolates; "dark" is fixed. */
function systemComment(name: string): string {
	return [
		'/* ==========================================================================',
		' * System preference: dark, until an explicit choice overrides it.',
		` * :not([data-theme]) is what makes that choice win: set data-theme="${name}"`,
		' * (or "dark") anywhere on <html> and this block stops matching. You need',
		' * no script to FOLLOW the system, only to OVERRIDE it. Scoped to :root',
		' * because it only ever answers "what should the page default to".',
		' * ========================================================================== */'
	].join('\n');
}

/** Default-theme banner — the block describes itself by name. */
function defaultComment(name: string): string {
	return [
		'/* ==========================================================================',
		` * Default theme "${name}": the :root block, re-declared so it can be RESTORED.`,
		' * :root defaults inherit as computed values, so a section switched back to',
		' * the default inside a dark page would otherwise keep the dark values it',
		' * inherited: there has to be something to switch back TO. Only the tokens',
		' * some theme actually changes are listed. The rest were never at risk.',
		' * ========================================================================== */'
	].join('\n');
}

/** Per-theme block banner. */
function themeComment(name: string): string {
	return [
		'/* ==========================================================================',
		` * Theme "${name}": activated by data-theme="${name}" on any element.`,
		' * ========================================================================== */'
	].join('\n');
}

// ---------------------------------------------------------------------------
// Emission helpers
// ---------------------------------------------------------------------------

function banner(lines: string[], indent: string): string {
	const bar = '='.repeat(69);
	return [
		`${indent}/* ${bar}`,
		...lines.map((l) => `${indent} * ${l}`),
		`${indent} * ${bar} */`
	].join('\n');
}

function note(lines: string[], indent: string): string {
	if (lines.length === 1) return `${indent}/* ${lines[0]} */`;
	return (
		[`${indent}/* ${lines[0]}`, ...lines.slice(1).map((l) => `${indent} * ${l}`)].join('\n') + ' */'
	);
}

function declarations(entries: TokenEntry[], indent: string, withNotes: boolean): string[] {
	const out: string[] = [];
	for (const entry of entries) {
		const noteLines = withNotes ? TOKEN_NOTES[entry.cssName] : undefined;
		if (noteLines) out.push(note(noteLines, indent));
		out.push(`${indent}${entry.cssName}: ${entry.value};`);
	}
	return out;
}

type DensityLevel = { near: number; away: number };

/** `--hz-density-ladder-depth-<n>` — the 1-based public rung name for a level. */
function densityRungName(depth: number): string {
	return `--hz-density-ladder-depth-${depth}`;
}

/**
 * The rung's own literal fallback: `config.tokens.density.ladder`'s value for
 * this depth when the config set one (specs/65 R21 — substituted verbatim,
 * not wrapped in another `calc()`), else `levels[depth - 1]`'s near
 * multiplier, exactly as before the config could touch this.
 */
function densityRungFallback(
	levels: readonly DensityLevel[],
	ladder: Readonly<Record<number, string>>,
	depth: number
): string {
	return ladder[depth] ?? `calc(var(--hz-density) * ${levels[depth - 1].near})`;
}

/** `var(--hz-density-ladder-depth-<n>, <its own literal fallback>)`. */
function densityRungRef(
	levels: readonly DensityLevel[],
	ladder: Readonly<Record<number, string>>,
	depth: number
): string {
	return `var(${densityRungName(depth)}, ${densityRungFallback(levels, ladder, depth)})`;
}

/**
 * Four rules — one per `density.levels` depth — each declaring
 * `--hz-space-near`/`--hz-space-away` as a `var()` lookup against a public
 * rung, never a bare `calc()`. No rung is ever declared here (R11): the
 * lookup form is what lets a consumer override a rung from ANYWHERE —
 * `:root`, a section, inside a `@layer` — with no cascade fight against an
 * unlayered declaration in this sheet.
 *
 * A level's `near` references its own depth's rung. Its `away` references
 * the next-shallower depth's rung — the ladder rule ("a level's away equals
 * the next-shallower level's near") — except at depth 1 (`body`), which has
 * no shallower rung: its away is its own rung, doubled. Both are asserted
 * against `density.levels` rather than assumed, so a metadata row that
 * breaks the ladder rule is a generator error naming the level, not a
 * silently unhooked declaration.
 */
function densityBlock(resolved: ResolvedConfig): string {
	const levels = resolved.density.levels;
	const ladder = resolved.density.ladder;
	const rules = levels.map((level, index) => {
		const depth = index + 1;
		const selector = index === 0 ? 'body' : `body ${'[data-density-shift] '.repeat(index).trim()}`;
		const near = densityRungRef(levels, ladder, depth);

		let away: string;
		if (index === 0) {
			if (level.away !== level.near * 2) {
				throw new HyzerConfigError(
					`density.levels[0].away (${level.away}) must equal density.levels[0].near x 2 ` +
						`(${level.near * 2}) - the top rung has no shallower rung to point at, so its away ` +
						'must be its own rung, doubled.'
				);
			}
			away = `calc(${near} * 2)`;
		} else {
			const prevNear = levels[index - 1].near;
			if (level.away !== prevNear) {
				throw new HyzerConfigError(
					`density.levels[${index}].away (${level.away}) must equal density.levels[${index - 1}].near ` +
						`(${prevNear}) - a level's away must equal the next-shallower level's near.`
				);
			}
			away = densityRungRef(levels, ladder, depth - 1);
		}

		return [
			`${selector} {`,
			`\t--hz-space-near: ${near};`,
			`\t--hz-space-away: ${away};`,
			'}'
		].join('\n');
	});
	return rules.join('\n\n');
}

/**
 * Theme-block selector: plain hook at :root, compound + descendant when scoped
 * (the scope element may carry data-theme itself, or inherit it from an
 * ancestor like <html>).
 *
 * The scoped pair is emitted one selector per line: generated sheets are
 * committed, so `prettier --check .` sees them, and a comma-joined pair of
 * this length is exactly what Prettier would break. Matching its output keeps
 * the drift test and the lint suite from contradicting each other.
 */
function themeSelector(selector: string, name: string): string {
	if (selector === ':root') return `[data-theme='${name}']`;
	return `${selector}[data-theme='${name}'],\n[data-theme='${name}'] ${selector}`;
}

// ---------------------------------------------------------------------------
// Custom intent wiring — one switch rule per config-added intent, wiring the
// reference theme's private --_c hook (the single switch button/banner/
// loading now alias, and badge/alert/blockquote already used).
// ---------------------------------------------------------------------------

/** The intent keys the base library ships — what R2 subtracts to find what a config ADDED rather than re-valued. */
const BASE_INTENT_KEYS = new Set(Object.keys(baseIntent));

/**
 * Every intent key a resolved config adds beyond the base vocabulary,
 * deduplicated by key, discovery order: the root `intent` section first,
 * then each theme's own `intent` list (dark, then every named theme, in
 * declaration order) — the same `[resolved.dark, ...resolved.themes]` scan
 * order used throughout this file. A built-in key a theme merely re-values
 * (Ocean's `neutral` remap) is excluded: the reference theme already wires
 * every built-in, in every theme, for free (the switch reads
 * `var(--hz-intent-<name>)`, which each `[data-theme=…]` block retargets).
 */
function customIntentKeys(resolved: ResolvedConfig): string[] {
	const seen = new Set<string>();
	const keys: string[] = [];
	const sources = [
		resolved.sections.find((s) => s.id === 'intent')!.entries,
		resolved.dark.intent,
		...resolved.themes.map((theme) => theme.intent)
	];
	for (const entries of sources) {
		for (const entry of entries) {
			if (BASE_INTENT_KEYS.has(entry.key) || seen.has(entry.key)) continue;
			seen.add(entry.key);
			keys.push(entry.key);
		}
	}
	return keys;
}

/**
 * Selector(s) for one end-of-sheet, unlayered, zero-specificity rule whose
 * target is `target` (an attribute selector, a component class, …) —
 * themeSelector()'s sibling, not a copy: the pieces differ enough (the scope
 * class is the ANCESTOR of the switching attribute/class here, rather than a
 * possible descendant of it — the target always lives inside the scoped
 * subtree, unlike `data-theme`, which may sit on `<html>` above it) that
 * sharing one function would need as much branching as two.
 *
 * Each line is independently wrapped in its own `:where()` (specificity
 * 0,0,0), matching the sheet-level cascade posture below: unlayered and
 * zero-specificity beats every layered reference-theme declaration and
 * loses to any consumer rule, layered or not — the same posture
 * `generateUtilitiesCss` uses (specs/44, "a deliberately-applied utility
 * beats the layered reference theme"). Serves both the custom-intent section
 * and the component-hooks section (specs/65 R14).
 */
function targetSelectors(selector: string, target: string): string[] {
	if (selector === ':root') return [`:where(${target})`];
	return [`:where(${selector} ${target})`, `:where(${selector}${target})`];
}

/**
 * Selector(s) for one custom-intent switch rule. Adds the one axis
 * `targetSelectors()` itself never needs: a camelCase key selects on both
 * attribute-value spellings (the raw config key and its kebab form), since
 * either is a plausible thing to pass to `intent=`.
 */
function intentSelectors(selector: string, key: string): string[] {
	const attrValues = key === toKebab(key) ? [key] : [key, toKebab(key)];
	return attrValues.flatMap((value) => targetSelectors(selector, `[data-intent='${value}']`));
}

const CUSTOM_INTENT_BANNER = [
	'Custom intent wiring',
	'One rule per intent your config adds beyond the seven the library ships.',
	'Each rule switches the same private --_c hook every reference-theme',
	'component reads, so a registered intent paints everywhere and you write',
	'no CSS of your own.',
	'No literal fallback: this sheet declares the token each rule points at,',
	'so a name that resolves nowhere fails loudly rather than painting a',
	'plausible wrong color.'
];

function customIntentRule(selector: string, key: string): string {
	const lines = [
		`${intentSelectors(selector, key).join(',\n')} {`,
		`\t--_c: var(--hz-intent-${toKebab(key)});`,
		'}'
	];
	return lines.join('\n');
}

/** Appended at the end of the sheet, in both full and overrides mode. Empty when the config adds no custom intent. */
function customIntentSection(resolved: ResolvedConfig, selector: string): string[] {
	const keys = customIntentKeys(resolved);
	if (keys.length === 0) return [];
	const parts: string[] = ['', banner(CUSTOM_INTENT_BANNER, '')];
	for (const key of keys) parts.push('', customIntentRule(selector, key));
	return parts;
}

// ---------------------------------------------------------------------------
// Component hooks (specs/65 R14) — one rule per owning class (or, for a ROOT
// hook, the sheet's own root) for every tokens.components entry, at the very
// end of the sheet, in both modes.
// ---------------------------------------------------------------------------

const COMPONENT_HOOKS_BANNER = [
	'Component hooks',
	'One rule per component your config sets a hook value for.',
	'A hook the reference theme declares on the component itself lands there',
	'too, so the value you set reaches that component directly. Otherwise it',
	"would inherit from the root, and the component's own declaration would",
	'ignore it.',
	'A hook the theme declares at :root, or never declares at all, lands at',
	"this sheet's own root: where the theme puts it, or would put it. An",
	'override you write on an ancestor then still reaches every instance',
	'below it. A declaration on the component itself would beat that',
	'override.',
	'Unlayered and zero specificity, the same posture as the custom intent',
	'section above: any rule you write for the same property still wins.'
];

/**
 * Selector for a ROOT-targeted hook group: the sheet's own scope selector,
 * :where-wrapped for the same zero-specificity reason as targetSelectors()
 * below — a consumer rule for the property still wins regardless of source
 * order. No compound/descendant pair to emit here: targetSelectors() needs
 * one because a class can sit either inside the scope or ON it; a ROOT hook
 * has no class of its own to be ambiguous with — the scope selector itself
 * is the target.
 */
function rootTargetSelectors(selector: string): string[] {
	return [`:where(${selector})`];
}

/** One rule for every hook the config set on `on` — `.${on}`, or the sheet's root for a ROOT group. */
function componentHookRule(selector: string, on: string, entries: TokenEntry[]): string {
	const selectors =
		on === ROOT ? rootTargetSelectors(selector) : targetSelectors(selector, `.${on}`);
	const lines = [
		`${selectors.join(',\n')} {`,
		...entries.map((e) => `\t${e.cssName}: ${e.value};`),
		'}'
	];
	return lines.join('\n');
}

/**
 * Appended at the very end of the sheet, after the custom-intent section, in
 * both full and overrides mode. Empty when the config sets no hook. Grouped
 * by `on` (an owning class, or the ROOT sentinel — every ROOT hook shares one
 * rule), in `componentHooks` order; within a rule, the config's own key order
 * (`resolved.components` is already in that order, seeded from `[]`) — same
 * resolved config, same bytes.
 */
function componentHookSection(resolved: ResolvedConfig, selector: string): string[] {
	if (resolved.components.length === 0) return [];
	const byOn = new Map<string, TokenEntry[]>();
	for (const entry of resolved.components) {
		const hook = componentHooks.find((h) => h.name === entry.cssName)!;
		if (!byOn.has(hook.on)) byOn.set(hook.on, []);
		byOn.get(hook.on)!.push(entry);
	}
	const onOrder: string[] = [];
	for (const hook of componentHooks) {
		if (byOn.has(hook.on) && !onOrder.includes(hook.on)) onOrder.push(hook.on);
	}
	const parts: string[] = ['', banner(COMPONENT_HOOKS_BANNER, '')];
	for (const on of onOrder) parts.push('', componentHookRule(selector, on, byOn.get(on)!));
	return parts;
}

/** Custom-property names referenced by var() inside a token value. */
function varRefs(value: string): string[] {
	return [...value.matchAll(/var\(\s*(--[a-z0-9-]+)/gi)].map((m) => m[1]);
}

/**
 * The tokens a SCOPED override sheet must re-declare: everything the config
 * touched, plus the transitive closure of tokens whose values depend on them.
 *
 * Why this exists. The two-layer color model is built on indirection —
 * `--hz-intent-primary: var(--hz-palette-primary)` — and var() inside a custom
 * property is substituted at computed-value time ON THE ELEMENT THE
 * DECLARATION APPLIES TO. At `:root` that is exactly what we want: an
 * override of `--hz-palette-primary` lands on the same element as the intent
 * declaration, so the cascade picks the new value and the whole chain
 * re-resolves.
 *
 * Scoped to a class it breaks. `.theme-ocean { --hz-palette-primary: #0f766e }`
 * leaves `--hz-intent-primary` declared back at `:root`, where it already
 * computed to the BASE blue and inherits down as that resolved value — so
 * every component reading the intent vocabulary (Button, Badge, Alert) keeps
 * the base palette while the panel swears it is teal.
 *
 * Re-emitting the dependents under the scope re-resolves them against the
 * scope's own values. The seed includes dark-block entries: a hue overridden
 * only in dark still needs its intent chain declared locally, or the dark
 * block has nothing to feed.
 */
function closureFrom(resolved: ResolvedConfig, seed: Iterable<string>): Set<string> {
	const included = new Set<string>(seed);
	const all = resolved.sections.flatMap((s) => s.entries);
	for (let changed = true; changed; ) {
		changed = false;
		for (const e of all) {
			if (included.has(e.cssName)) continue;
			if (varRefs(e.value).some((ref) => included.has(ref))) {
				included.add(e.cssName);
				changed = true;
			}
		}
	}
	return included;
}

function scopedClosure(resolved: ResolvedConfig): Set<string> {
	const seed: string[] = [];
	for (const section of resolved.sections) {
		for (const e of section.entries) if (e.fromConfig) seed.push(e.cssName);
	}
	for (const e of themeOwn(resolved.dark)) {
		if (e.fromConfig) seed.push(e.cssName);
	}
	return closureFrom(resolved, seed);
}

/** A theme's own declarations, in emission order (roles, hues, intents, rest). */
function themeOwn(theme: ResolvedTheme): TokenEntry[] {
	return [...theme.color, ...theme.palette, ...theme.intent, ...theme.rest];
}

/**
 * A theme block: what the theme itself declares, plus the derived chain it
 * must re-declare to work on ANY element rather than only on `<html>`.
 *
 * Why the dependents exist. `--hz-intent-primary: var(--hz-palette-primary)`
 * is declared at `:root`, and var() inside a custom property is substituted
 * at computed-value time on the element the declaration applies to. When the
 * theme block lands on `<html>` — the same element as `:root` — the override
 * and the chain meet there and everything re-resolves. Land it on a
 * `<section>` instead and the intents have already computed at `:root` to the
 * default palette, inheriting down as fixed values: a dark section with
 * light-blue buttons and light borders. Re-declaring the dependents inside
 * the block re-resolves them against the theme's own values, on whatever
 * element the block matched. At `:root` they are identical to the defaults
 * and cost nothing but bytes.
 *
 * This is the same problem `scopedClosure()` solves for scoped sheets, from
 * the other direction: there the SHEET is scoped, here the BLOCK is.
 */
function themeBlock(
	resolved: ResolvedConfig,
	theme: ResolvedTheme
): { own: TokenEntry[]; dependents: TokenEntry[] } {
	const own = themeOwn(theme);
	const ownNames = new Set(own.map((e) => e.cssName));
	const closure = closureFrom(resolved, ownNames);
	const dependents = resolved.sections
		.flatMap((s) => s.entries)
		.filter((e) => closure.has(e.cssName) && !ownNames.has(e.cssName));
	return { own, dependents };
}

// ---------------------------------------------------------------------------
// generateCss
// ---------------------------------------------------------------------------

export function generateCss(resolved: ResolvedConfig, options: GenerateOptions = {}): string {
	const mode = options.mode ?? 'full';
	const selector = options.selector ?? resolved.selector ?? ':root';
	// R2's backstop: the only guard a direct engine caller (gen-tokens.ts, a
	// docs page, a consumer build script) ever gets, since resolveConfig's own
	// check never sees a value passed straight through the option.
	assertSelector(selector, 'config.selector');
	return mode === 'full'
		? generateFull(resolved, selector, options.intro)
		: generateOverrides(resolved, selector, options.intro);
}

/** Weave optional intro lines into a generated header comment. */
function withIntro(header: string, intro: string[] | undefined): string {
	if (!intro || intro.length === 0) return header;
	const lines = header.split('\n');
	// After the opening '/**': the intro block, a spacer, then the stock text.
	return [lines[0], ...intro.map((l) => ` * ${l}`.trimEnd()), ' *', ...lines.slice(1)].join('\n');
}

/**
 * R4 — a scoped sheet's header names its scope, one line, immediately after
 * the identity line (`lines[1]`) and nothing else changes. `:root` gains
 * nothing, so an unscoped sheet's header is untouched. Applied before
 * `withIntro`, whose own insertion point (right after the opening `/**`) is
 * unaffected by a line further down.
 */
function withScope(header: string, selector: string): string {
	if (selector === ':root') return header;
	const lines = header.split('\n');
	return [lines[0], lines[1], ` * Scope: ${selector}`, ...lines.slice(2)].join('\n');
}

function generateFull(resolved: ResolvedConfig, selector: string, intro?: string[]): string {
	const parts: string[] = [withIntro(withScope(FULL_HEADER, selector), intro), `${selector} {`];

	resolved.sections.forEach((section, i) => {
		if (i > 0) parts.push('');
		parts.push(banner(SECTION_BANNERS[section.id], '\t'));
		parts.push(...declarations(section.entries, '\t', true));
		if (section.id === 'space') {
			parts.push('');
			parts.push(note(TOKEN_NOTES['--hz-density'], '\t'));
			parts.push(`\t--hz-density: ${resolved.density.unit};`);
		}
	});
	parts.push('}');

	parts.push('', DENSITY_COMMENT, densityBlock(resolved));

	// Every named theme is a [data-theme="<name>"] block of the same shape;
	// dark is one of them, and leads because the base itself authors it.
	const blocks = [resolved.dark, ...resolved.themes].map((theme) => ({
		theme,
		...themeBlock(resolved, theme)
	}));

	for (const { theme, own, dependents } of blocks) {
		const comment = theme.name === 'dark' ? DARK_COMMENT : themeComment(theme.name);
		parts.push('', comment, `${themeSelector(selector, theme.name)} {`);
		// Roles, then hues, then intents — sourced directly from the three
		// resolved lists (.3); no value-shape inference.
		parts.push(...declarations(theme.color, '\t', false));
		for (const group of [theme.palette, theme.intent, theme.rest]) {
			if (group.length === 0) continue;
			parts.push('');
			parts.push(...declarations(group, '\t', false));
		}
		if (dependents.length > 0) {
			parts.push('');
			parts.push(note(DERIVED_COMMENT, '\t'));
			parts.push(...declarations(dependents, '\t', false));
		}
		parts.push('}');

		// The system default carries the theme's OWN declarations only: it
		// applies at :root, where the chain declared above it re-resolves on
		// the same element, so the derived block would be pure duplication.
		if (theme.name === 'dark' && selector === ':root') {
			parts.push(
				'',
				systemComment(resolved.defaultThemeName),
				'@media (prefers-color-scheme: dark) {'
			);
			parts.push('\t:root:not([data-theme]) {');
			parts.push(...declarations(own, '\t\t', false));
			parts.push('\t}');
			parts.push('}');
		}
	}

	const restore = defaultRestore(resolved, blocks);
	if (restore.length > 0) {
		parts.push(
			'',
			defaultComment(resolved.defaultThemeName),
			`${themeSelector(selector, resolved.defaultThemeName)} {`
		);
		parts.push(...declarations(restore, '\t', false));
		parts.push('}');
	}

	parts.push(...customIntentSection(resolved, selector));
	parts.push(...componentHookSection(resolved, selector));

	return parts.join('\n') + '\n';
}

/**
 * The default block (`[data-theme="<resolved.defaultThemeName>"]`): every
 * token any theme block declares, restored to its default value.
 *
 * A token a theme introduces but `:root` never defines (a consumer's
 * dark-only intent, say) restores to `initial` — the guaranteed-invalid
 * value, which is what "not declared here" means for a custom property, so
 * `var()` falls back exactly as it does outside the theme.
 *
 * `--hz-density` is the one exception: it lives outside `resolved.sections`
 * (emitted by hand inside the `space` section), so it is never "not declared
 * here" — a theme that sets `density.unit` must restore to the root unit,
 * never `initial`, or every `calc(var(--hz-density) * N)` in the ladder goes
 * invalid at computed-value time. Spliced into root order right after the
 * space section's entries, where the full sheet emits it.
 */
function defaultRestore(
	resolved: ResolvedConfig,
	blocks: { own: TokenEntry[]; dependents: TokenEntry[] }[]
): TokenEntry[] {
	const changed = new Set<string>();
	for (const block of blocks) {
		for (const e of [...block.own, ...block.dependents]) changed.add(e.cssName);
	}
	const densityEntry: TokenEntry = {
		cssName: '--hz-density',
		key: 'density',
		value: resolved.density.unit,
		fromConfig: false
	};
	// :root order, so the block reads like the sheet it restores; tokens no
	// :root section defines follow at the end.
	const rootEntries = resolved.sections.flatMap((s) =>
		s.id === 'space' ? [...s.entries, densityEntry] : s.entries
	);
	const defined = new Set(rootEntries.map((e) => e.cssName));
	return [
		...rootEntries.filter((e) => changed.has(e.cssName)),
		...[...changed]
			.filter((cssName) => !defined.has(cssName))
			.map((cssName) => ({ cssName, key: cssName, value: 'initial', fromConfig: false }))
	];
}

function generateOverrides(resolved: ResolvedConfig, selector: string, intro?: string[]): string {
	const scoped = selector !== ':root';
	const header = withIntro(
		withScope(
			[
				'/**',
				' * @hyzer-labs/ui token overrides',
				' *',
				' * GENERATED FILE - do not edit by hand (hyzer generate --mode overrides).',
				...(scoped
					? [
							' * Config-touched tokens, plus every token that derives from them. A',
							' * scoped sheet must re-declare the derived Layer-2 chain: a var()',
							' * indirection declared at :root already resolved there, and inherits',
							' * down as a fixed value.',
							' * Import this sheet AFTER @hyzer-labs/ui/tokens.css so the overrides',
							' * win by source order.'
						]
					: [
							' * This sheet carries only the tokens your config touched. Import it',
							' * AFTER @hyzer-labs/ui/tokens.css so the overrides win by source order.'
						]),
				' */'
			].join('\n'),
			selector
		),
		intro
	);

	// Scoped sheets carry the derived chain too — see scopedClosure().
	const emit = scoped ? scopedClosure(resolved) : null;
	const rootEntries = resolved.sections.flatMap((s) =>
		s.entries.filter((e) => (emit ? emit.has(e.cssName) : e.fromConfig))
	);

	/**
	 * The dark block needs the same treatment for a different reason. A base
	 * dark entry like surface-muted's stronger tint
	 * (`color-mix(… var(--hz-palette-gray) 25%, var(--hz-color-surface))`) is
	 * declared at :root's dark block. Scoped, it never reaches the subtree, and
	 * the scope's own light-block declaration would silently keep applying its
	 * 6% light-mode tint in dark. Re-emit any dark entry that derives from a
	 * token the scope redeclares.
	 */
	const darkDerives = (e: TokenEntry) =>
		emit !== null && varRefs(e.value).some((ref) => emit.has(ref));
	/**
	 * R1 — the sheet emits the dark theme's own value for every token the
	 * sheet declares at its root, not only what the consumer authored under
	 * `themes.dark`. Otherwise the cascade disagrees with full mode: a root
	 * override with no dark counterpart falls through to the base sheet's dark
	 * block on whatever element carries data-theme="dark", while the contrast
	 * report grades resolved.dark — which always has the seeded companion.
	 */
	const rootNames = new Set(rootEntries.map((e) => e.cssName));
	const keepDark = (e: TokenEntry) => e.fromConfig || rootNames.has(e.cssName) || darkDerives(e);
	const darkEntries = [
		...resolved.dark.color.filter(keepDark),
		...resolved.dark.palette.filter(keepDark),
		...resolved.dark.intent.filter(keepDark),
		...resolved.dark.rest.filter(keepDark)
	];

	const parts: string[] = [header];
	const hasRoot = rootEntries.length > 0 || resolved.density.unitFromConfig;

	/**
	 * The light block below re-restores the tokens this sheet overrides, and it
	 * draws them from `rootEntries` — the same names with the same values. When
	 * every restored token is one this sheet already declares at the root, the
	 * two blocks would carry identical declarations, so they share one rule
	 * instead. Any token the root declares and light does not is a token no
	 * theme changes, which makes declaring it under light harmless.
	 */
	const restorableNames = new Set(
		defaultRestore(resolved, [
			themeBlock(resolved, resolved.dark),
			...resolved.themes.map((theme) => themeBlock(resolved, theme))
		]).map((e) => e.cssName)
	);
	// A theme block declaring --hz-density forces mergeDefault off too — same
	// reason as unitFromConfig above (R5): the merged root+light rule would
	// declare the default unit at the scope selector and clobber a consumer's
	// own --hz-density override inside that scope.
	const mergeDefault =
		hasRoot &&
		rootEntries.some((e) => restorableNames.has(e.cssName)) &&
		!resolved.density.unitFromConfig &&
		!restorableNames.has('--hz-density');

	if (hasRoot) {
		parts.push(
			mergeDefault
				? `${selector},\n${themeSelector(selector, resolved.defaultThemeName)} {`
				: `${selector} {`
		);
		parts.push(...declarations(rootEntries, '\t', false));
		if (resolved.density.unitFromConfig) parts.push(`\t--hz-density: ${resolved.density.unit};`);
		parts.push('}');
	}
	if (darkEntries.length > 0) {
		if (hasRoot) parts.push('');
		parts.push(`${themeSelector(selector, 'dark')} {`);
		parts.push(...declarations(darkEntries, '\t', false));
		parts.push('}');
	}

	// Named themes are entirely the consumer's authoring — every entry is
	// fromConfig, so the whole block is an override by definition. Each still
	// carries its derived chain, for the same reason the full sheet's do.
	let emitted = hasRoot || darkEntries.length > 0;
	const themeBlocks = resolved.themes.map((theme) => ({ theme, ...themeBlock(resolved, theme) }));
	for (const { theme, own, dependents } of themeBlocks) {
		if (own.length === 0) continue;
		if (emitted) parts.push('');
		parts.push(`${themeSelector(selector, theme.name)} {`);
		parts.push(...declarations(own, '\t', false));
		if (dependents.length > 0) {
			parts.push('');
			parts.push(note(DERIVED_COMMENT, '\t'));
			parts.push(...declarations(dependents, '\t', false));
		}
		parts.push('}');
		emitted = true;
	}

	// The base sheet's light block restores the BASE defaults — which would
	// undo this sheet's own :root overrides inside a light-scoped section.
	// Re-restore the tokens this sheet redeclares, after it in source order.
	const restorable = new Set(
		defaultRestore(resolved, [themeBlock(resolved, resolved.dark), ...themeBlocks]).map(
			(e) => e.cssName
		)
	);
	const restore = mergeDefault ? [] : rootEntries.filter((e) => restorable.has(e.cssName));
	// --hz-density never lives in rootEntries (it's outside resolved.sections),
	// so a theme block that declares it is spliced in here, last — mirroring
	// where the root block puts it — rather than picked up by the filter above.
	if (restorable.has('--hz-density')) {
		restore.push({
			cssName: '--hz-density',
			key: 'density',
			value: resolved.density.unit,
			fromConfig: false
		});
	}
	if (restore.length > 0) {
		if (emitted) parts.push('');
		parts.push(`${themeSelector(selector, resolved.defaultThemeName)} {`);
		parts.push(...declarations(restore, '\t', false));
		parts.push('}');
		emitted = true;
	}

	const intentSection = customIntentSection(resolved, selector);
	if (intentSection.length > 0) emitted = true;
	const hookSection = componentHookSection(resolved, selector);
	if (hookSection.length > 0) emitted = true;

	if (!emitted) {
		parts.push('/* No overrides configured. */');
	}
	parts.push(...intentSection, ...hookSection);
	return parts.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// themeVars — the same block, as a flat map for runtime use
// ---------------------------------------------------------------------------

/**
 * The custom properties a theme override sets, resolved and flattened: the
 * theme's own declarations plus the derived chain, exactly what the generated
 * `[data-theme="…"]` block contains.
 *
 * Backs the inline form of the `theme()` attachment, which writes these
 * straight onto an element's `style`. The derived chain matters just as much
 * there as it does in a stylesheet — inline custom properties are still
 * declarations on one element, so an inline palette override without its
 * chain themes the surface and leaves the buttons behind.
 *
 * Throws `HyzerConfigError` on an invalid override, same as `resolveConfig`.
 */
export function themeVars(override: HyzerThemeOverride): Record<string, string> {
	const resolved = resolveConfig({ themes: { runtime: override } });
	const { own, dependents } = themeBlock(resolved, resolved.themes[0]);
	return Object.fromEntries([...own, ...dependents].map((e) => [e.cssName, e.value]));
}

// ---------------------------------------------------------------------------
// generateUtilitiesCss — the opt-in utility sheet
// ---------------------------------------------------------------------------

export interface GenerateUtilitiesOptions {
	/**
	 * Extra description lines prepended inside the generated header comment —
	 * same weaving as `GenerateOptions.intro`.
	 */
	intro?: string[];
}

const UTILITIES_HEADER = [
	'/**',
	' * @hyzer-labs/ui utilities',
	' *',
	' * GENERATED FILE - do not edit by hand.',
	' * Generated by `hyzer generate --utilities` (or set `utilities` in your',
	' * hyzer.config) from your tokens. Regenerate rather than editing here:',
	' * any hand edits are lost on the next run.',
	' *',
	' * Opt in by importing this sheet explicitly, like a theme sheet',
	' * (`@hyzer-labs/ui/utilities.css`). If you never import it, none of these',
	' * bytes ship.',
	' *',
	' * Definition: a utility class is a token-derived, single-property helper.',
	' * One class, one declaration, resolved from a design token. That is the',
	' * whole definition; it does not depend on where the class is or is not',
	' * used.',
	' *',
	' * Anti-goal: utilities are for ad-hoc spots (nudging one element, tinting',
	' * one line of text), not an alternative layout system.',
	' * Components already own their spacing (gap/padding props, the',
	' * data-padding/data-gap scales) and the density system',
	' * (--hz-space-near/--hz-space-away). The utility sheet deliberately',
	' * does not reproduce that surface: it exposes the fixed --hz-space-*',
	' * scale for margins only, never the density near/away distances, and',
	' * no padding helpers at all (padding is owned by components).',
	' *',
	' * Unlayered, single-class specificity (0,1,0), no !important. This',
	' * mirrors .sr-only: a deliberately-applied utility beats the layered',
	' * reference theme, while your own unlayered class of equal specificity',
	' * still wins by source order.',
	' */'
].join('\n');

const COLOR_UTILITIES_BANNER = [
	'Color utilities',
	'Role + intent helpers for text, background, border and fill, resolved from',
	'--hz-color-* / --hz-intent-*. One property each: .hz-border-* sets only',
	'border-color, so bring your own border-width/style; .hz-fill-* is for SVG.',
	'Components that own a surface (Badge, Alert, Banner) keep doing so.',
	'These are for ad-hoc spots, not for restyling a component.'
];

/**
 * The four color-utility families, fixed emission order. Each emits its
 * role helpers first, then one class per resolved intent. A `suffix` of `''`
 * is the bare family class (`.hz-text`, `.hz-bg`).
 */
const COLOR_FAMILIES: readonly {
	prefix: string;
	property: string;
	roles: readonly { suffix: string; role: string }[];
}[] = [
	{
		prefix: 'hz-text',
		property: 'color',
		roles: [
			{ suffix: '', role: 'text' },
			{ suffix: 'muted', role: 'textMuted' }
		]
	},
	{
		prefix: 'hz-bg',
		property: 'background-color',
		roles: [
			{ suffix: '', role: 'surface' },
			{ suffix: 'muted', role: 'surfaceMuted' }
		]
	},
	{
		prefix: 'hz-border',
		property: 'border-color',
		roles: [{ suffix: '', role: 'border' }]
	},
	{
		prefix: 'hz-fill',
		property: 'fill',
		roles: [
			{ suffix: '', role: 'text' },
			{ suffix: 'muted', role: 'textMuted' }
		]
	}
];

const MARGIN_UTILITIES_BANNER = [
	'Margin utilities (logical properties)',
	'Seven families per --hz-space-* rung: margin, margin-block(-start/-end),',
	'margin-inline(-start/-end). No padding: components own their own padding.'
];

/** The seven logical margin families, fixed emission order. */
const MARGIN_FAMILIES: readonly { suffix: string; property: string }[] = [
	{ suffix: '', property: 'margin' },
	{ suffix: 'block', property: 'margin-block' },
	{ suffix: 'block-start', property: 'margin-block-start' },
	{ suffix: 'block-end', property: 'margin-block-end' },
	{ suffix: 'inline', property: 'margin-inline' },
	{ suffix: 'inline-start', property: 'margin-inline-start' },
	{ suffix: 'inline-end', property: 'margin-inline-end' }
];

function utilityRule(className: string, property: string, value: string): string {
	return `.${className} {\n\t${property}: ${value};\n}`;
}

/**
 * Renders the opt-in utility sheet from the resolved token model: four color
 * families (`hz-text`, `hz-bg`, `hz-border`, `hz-fill`), each emitting its
 * role helpers plus one class per resolved intent, and the seven logical
 * margin families per resolved space rung.
 * Deterministic and unlayered — mirrors `.sr-only`'s specificity posture.
 * Does NOT re-resolve tokens; reads only `resolved.sections`.
 */
export function generateUtilitiesCss(
	resolved: ResolvedConfig,
	options: GenerateUtilitiesOptions = {}
): string {
	const roles = resolved.sections.find((s) => s.id === 'roles')!.entries;
	const intentEntries = resolved.sections.find((s) => s.id === 'intent')!.entries;
	const spaceEntries = resolved.sections.find((s) => s.id === 'space')!.entries;

	const parts: string[] = [withIntro(UTILITIES_HEADER, options.intro)];

	// --- color utilities --------------------------------------------------
	parts.push('', banner(COLOR_UTILITIES_BANNER, ''));

	for (const family of COLOR_FAMILIES) {
		// Utility-class-namespace collision tracking, per family (edge case: a
		// consumer intent named "muted" kebab-cases to the fixed .hz-text-muted
		// role helper's class name) — a hard generation error naming both
		// parties, mirroring the engine's existing kebab-collision rule
		// (schema.ts).
		const usedClasses = new Map<string, string>();

		for (const { suffix, role } of family.roles) {
			const entry = roles.find((e) => e.key === role);
			if (!entry) {
				throw new HyzerConfigError(
					`generateUtilitiesCss requires the "${role}" color role (for the .${family.prefix} utility family).`
				);
			}
			const className = suffix ? `${family.prefix}-${suffix}` : family.prefix;
			usedClasses.set(className, `the "${role}" role helper (.${className})`);
			parts.push('', utilityRule(className, family.property, `var(${entry.cssName})`));
		}

		for (const entry of intentEntries) {
			const className = `${family.prefix}-${toKebab(entry.key)}`;
			const owner = usedClasses.get(className);
			if (owner) {
				throw new HyzerConfigError(
					`config.tokens.intent.${entry.key} kebab-cases to the utility class ".${className}", ` +
						`which ${owner} already defines. Rename the intent to avoid the collision.`
				);
			}
			usedClasses.set(className, `intent "${entry.key}" (config.tokens.intent.${entry.key})`);
			parts.push('', utilityRule(className, family.property, `var(${entry.cssName})`));
		}
	}

	// --- margin utilities -------------------------------------------------
	parts.push('', banner(MARGIN_UTILITIES_BANNER, ''));
	for (const family of MARGIN_FAMILIES) {
		for (const rung of spaceEntries) {
			const rungSuffix = toKebab(rung.key);
			const className = family.suffix
				? `hz-m-${family.suffix}-${rungSuffix}`
				: `hz-m-${rungSuffix}`;
			parts.push('', utilityRule(className, family.property, `var(${rung.cssName})`));
		}
	}

	return parts.join('\n') + '\n';
}
